export default `
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const genericNames=new Set(['empresa local','empresa','local business','business','dentista','clínica','clinica','advogado','arquiteto','contador','fisioterapia','salão de beleza','salao de beleza','academia','restaurante','imobiliária','imobiliaria']);
let results=[],saved=JSON.parse(localStorage.getItem('site-sales-os:leads')||'[]').filter(x=>x&&cleanName(x.name)&&x.websiteStatus!=='found'),selected=null,goal='first-contact',capabilities={foursquarePlaces:false,webSearch:false};
const stages=[['new','novo'],['contacted','contatado'],['replied','respondeu'],['proposal','proposta'],['won','ganho'],['lost','perdido']];
const overpassEndpoints=['https://overpass.kumi.systems/api/interpreter','https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter'];
const map=L.map('map').setView([-23.55,-46.63],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);let markers=[];
const esc=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function persist(){localStorage.setItem('site-sales-os:leads',JSON.stringify(saved));stats()}
function stats(){$('#leadCount').textContent=results.length;$('#savedCount').textContent=saved.length}
function cleanPhone(s=''){return String(s).replace(/[^\\d+]/g,'')}
function cleanName(s=''){const v=String(s||'').replace(/\\s+/g,' ').trim();if(!v||v.length<2||genericNames.has(v.toLowerCase())||/^\\d+[a-z]?$/i.test(v)||/^(rua|r\.|avenida|av\.|alameda|travessa|praça|praca|largo|rodovia|estrada|viel[ae]|beco)\\b/i.test(v))return'';return v}
function osmName(t={}){return cleanName(t.name)||cleanName(t['name:pt'])||cleanName(t.brand)||cleanName(t.operator)||cleanName(t.official_name)||cleanName(t.short_name)||cleanName(t.alt_name)||cleanName(t['contact:name'])||''}
function osmLead(el){const t=el.tags||{},lat=el.lat??el.center?.lat,lng=el.lon??el.center?.lon,name=osmName(t);if(!name)return null;const website=t.website||t['contact:website']||'';return{id:'osm-'+el.type+'-'+el.id,source:'osm',verificationBasis:'osm',name,address:[t['addr:street'],t['addr:housenumber'],t['addr:suburb'],t['addr:city']].filter(Boolean).join(', '),lat,lng,phone:cleanPhone(t.phone||t['contact:phone']||''),email:t.email||t['contact:email']||'',website,mapsUrl:lat&&lng?'https://www.openstreetmap.org/?mlat='+lat+'&mlon='+lng+'#map=18/'+lat+'/'+lng:'',rating:null,reviews:0,type:t.amenity||t.office||t.shop||t.healthcare||t.leisure||'',instagram:t.instagram||t['contact:instagram']||'',status:'new',websiteStatus:website?'found':'unverified'}}
async function browserOverpass(query){const errors=[];for(const endpoint of overpassEndpoints){try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);const r=await fetch(endpoint+'?data='+encodeURIComponent(query),{signal:c.signal,headers:{Accept:'application/json'}});clearTimeout(timer);if(!r.ok){errors.push(new URL(endpoint).host+':'+r.status);continue}const d=await r.json();const leads=(d.elements||[]).map(osmLead).filter(x=>x&&x.name&&x.lat&&x.lng).slice(0,80);return{leads,provider:'openstreetmap:'+new URL(endpoint).host}}catch(e){errors.push(new URL(endpoint).host+':'+(e.name||'erro'))}}throw Error(errors.join(', '))}
async function serverFallback(q){const r=await fetch('/api/fallback-leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(q)}),d=await r.json();if(!r.ok)throw Error(d.error||'Fallback indisponível');return{leads:(d.leads||[]).filter(x=>x&&cleanName(x.name)),provider:d.provider||'nominatim-fallback'}}
async function verifyCandidates(raw){const all=raw.filter(x=>x&&cleanName(x.name)),found=[],qualified=[],unverified=[];for(let i=0;i<all.length;i+=12){const chunk=all.slice(i,i+12);try{const r=await fetch('/api/verify-websites',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({leads:chunk})}),d=await r.json();if(r.ok){capabilities=d.capabilities||capabilities;const byId=new Map((d.results||[]).map(x=>[x.id,x]));chunk.forEach(l=>{const v=byId.get(l.id);if(v){l.websiteStatus=v.websiteStatus;l.website=v.website||l.website||'';l.websiteEvidence=v.evidence||'';l.verificationSources=v.sources||[]}})}}catch{}}
  for(const l of all){if(l.websiteStatus==='found'||l.website)found.push(l);else if(l.websiteStatus==='no_site_signal')qualified.push(l);else{l.websiteStatus='unverified';unverified.push(l)}}
  qualified.sort((a,b)=>(!!b.phone-!!a.phone)||a.name.localeCompare(b.name));unverified.sort((a,b)=>(!!b.phone-!!a.phone)||a.name.localeCompare(b.name));return{found,qualified,unverified}}
function statusLabel(l){if(l.websiteStatus==='found'||l.website)return'site encontrado';if(l.websiteStatus==='no_site_signal')return'sem site detectado · alta confiança';return'não verificado'}
function statusClass(l){return l.websiteStatus==='no_site_signal'?'verifiedNoSite':l.websiteStatus==='found'||l.website?'hasSite':'unverified'}
function manualSearchUrl(l){return'https://search.brave.com/search?q='+encodeURIComponent('"'+l.name+'" '+(l.address||''))}
function card(l,selectable=false){const d=document.createElement('article');d.className='leadCard '+statusClass(l);const site=l.websiteStatus==='found'||l.website,qualified=l.websiteStatus==='no_site_signal';d.innerHTML='<div class="leadTop"><div><h3>'+esc(l.name)+'</h3><p class="address">'+esc(l.address||'endereço não cadastrado')+'</p></div><span class="source">'+esc(l.source||'lead')+'</span></div><div class="meta"><span>'+statusLabel(l)+'</span>'+(l.phone?'<span>'+esc(l.phone)+'</span>':'<span>sem telefone</span>')+(l.email?'<span>'+esc(l.email)+'</span>':'')+(l.instagram?'<span>@'+esc(l.instagram)+'</span>':'')+'</div><div class="actions">'+(selectable?'':qualified?'<button class="saveBtn">salvar</button>':'<a class="mapBtn" target="_blank" href="'+manualSearchUrl(l)+'">revisar web</a>')+(l.website?'<a class="mapBtn" target="_blank" href="'+esc(l.website)+'">site</a>':'')+(l.phone?'<a class="waBtn" target="_blank" href="https://wa.me/'+l.phone.replace(/\\D/g,'')+'">WhatsApp</a>':'')+(l.mapsUrl?'<a class="mapBtn" target="_blank" href="'+esc(l.mapsUrl)+'">mapa</a>':'')+'</div>';if(selectable)d.onclick=()=>pick(l.id);else if(qualified)d.querySelector('.saveBtn').onclick=()=>save(l);return d}
function renderResults(){const r=$('#results');r.innerHTML='';if(!results.length){const mode=capabilities.foursquarePlaces&&capabilities.webSearch?'Nenhum lead passou pelo critério de alta confiança.':'A qualificação automática exige Foursquare + Brave Search. Sem as duas fontes, candidatos ficam em revisão.';r.innerHTML='<div class="empty"><strong>nenhum lead qualificado.</strong><span>'+mode+'</span></div>';return}results.forEach(l=>r.appendChild(card(l)))}
function draw(){markers.forEach(m=>m.remove());markers=[];results.forEach(l=>{const m=L.marker([l.lat,l.lng]).addTo(map).bindPopup('<b>'+esc(l.name)+'</b><br>'+esc(l.address||'')+'<br><small>'+statusLabel(l)+'</small>');markers.push(m)});if(markers.length)map.fitBounds(L.featureGroup(markers).getBounds().pad(.12))}
function save(l){if(l.websiteStatus!=='no_site_signal'||saved.some(x=>x.id===l.id))return;saved.unshift({...l,stage:'new'});persist();pipeline();copilot()}
function pipeline(){const root=$('#pipeline');root.innerHTML='';stages.forEach(([id,label])=>{const col=document.createElement('section');col.className='column';const ls=saved.filter(x=>(x.stage||'new')===id);col.innerHTML='<div class="columnHead"><b>'+label+'</b><span>'+ls.length+'</span></div>';ls.forEach(l=>{const d=document.createElement('article');d.className='deal';d.innerHTML='<h4>'+esc(l.name)+'</h4><p>'+esc(l.address||'')+'</p><select>'+stages.map(([sid,sl])=>'<option value="'+sid+'" '+(sid===id?'selected':'')+'>'+sl+'</option>').join('')+'</select><div class="dealActions"><button>copiloto</button><button>remover</button></div>';const bs=d.querySelectorAll('button');d.querySelector('select').onchange=e=>{l.stage=e.target.value;persist();pipeline()};bs[0].onclick=()=>{pick(l.id);view('copilot')};bs[1].onclick=()=>{saved=saved.filter(x=>x.id!==l.id);persist();pipeline();copilot()};col.appendChild(d)});root.appendChild(col)})}
function copilot(){const r=$('#copilotLeads');r.innerHTML='';saved.forEach(l=>r.appendChild(card(l,true)))}
function pick(id){selected=id;const l=saved.find(x=>x.id===id);$('#selectedLead').textContent=l?l.name+' · '+(l.address||'sem endereço'):'Nenhum lead selecionado.'}
async function search(e){e.preventDefault();const b=e.submitter||$('#searchForm .primary');b.disabled=true;b.textContent='buscando…';$('#providerLabel').textContent='descobrindo empresas…';try{const q={city:$('#city').value.trim(),niche:$('#niche').value,radius:Number($('#radius').value)};const r=await fetch('/api/leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(q)}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha');capabilities=d.capabilities||capabilities;let raw=[],provider=d.provider||'';if(d.overpassQuery){try{const osm=await browserOverpass(d.overpassQuery);raw=osm.leads;provider=osm.provider;if(!raw.length){const alt=await serverFallback(q);raw=alt.leads;provider=alt.provider}}catch{const alt=await serverFallback(q);raw=alt.leads;provider=alt.provider}}else raw=d.leads||[];$('#providerLabel').textContent='verificando presença web…';const checked=await verifyCandidates(raw);results=[...checked.qualified,...checked.unverified];$('#resultTitle').textContent=checked.qualified.length+' qualificados · '+checked.unverified.length+' revisão';const mode=(capabilities.foursquarePlaces?'Foursquare ✓':'Foursquare —')+' · '+(capabilities.webSearch?'Brave ✓':'Brave —');$('#providerLabel').textContent=provider+' · '+checked.found.length+' com site removidos · '+mode;renderResults();draw();stats();if(!results.length&&d.center)map.setView([d.center.lat,d.center.lng],12)}catch(x){$('#results').innerHTML='<div class="empty"><strong>busca indisponível.</strong><span>'+esc(x.message)+'</span></div>';$('#providerLabel').textContent='erro na consulta'}finally{b.disabled=false;b.textContent='buscar leads'}}
async function generate(){const l=saved.find(x=>x.id===selected);if(!l){$('#generatedText').textContent='Selecione um lead salvo primeiro.';return}const r=await fetch('/api/prospect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lead:l,goal,notes:$('#notes').value.trim()})}),d=await r.json();$('#generatedText').textContent=d.text||d.error||'Sem resposta.'}
function exportCsv(){const cols=['name','address','phone','email','instagram','websiteStatus','website','websiteEvidence','verificationSources','mapsUrl','stage'];const q=v=>'"'+String(Array.isArray(v)?v.join('|'):v||'').replace(/"/g,'""')+'"';const csv=[cols.join(','),...saved.map(l=>cols.map(c=>q(l[c])).join(','))].join('\\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='leads.csv';a.click()}
function view(n){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+n+'View').classList.add('active');$$('.navitem[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===n));if(n==='discovery')setTimeout(()=>map.invalidateSize(),30)}
$('#searchForm').onsubmit=search;$('#generateBtn').onclick=generate;$('#exportBtn').onclick=exportCsv;$('#clearSearch').onclick=()=>{results=[];renderResults();stats();markers.forEach(m=>m.remove());markers=[]};$$('.navitem[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('.goal').forEach(b=>b.onclick=()=>{$$('.goal').forEach(x=>x.classList.remove('active'));b.classList.add('active');goal=b.dataset.goal});$('#copyBtn').onclick=()=>navigator.clipboard.writeText($('#generatedText').textContent);persist();pipeline();copilot();
`;
