export default `
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let results=[],saved=JSON.parse(localStorage.getItem('site-sales-os:leads')||'[]'),selected=null,goal='first-contact';
const stages=[['new','novo'],['contacted','contatado'],['replied','respondeu'],['proposal','proposta'],['won','ganho'],['lost','perdido']];
const map=L.map('map').setView([-23.55,-46.63],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);let markers=[];
const esc=s=>String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function persist(){localStorage.setItem('site-sales-os:leads',JSON.stringify(saved));stats()}
function stats(){$('#leadCount').textContent=results.length;$('#savedCount').textContent=saved.length}
function card(l,selectable=false){const d=document.createElement('article');d.className='leadCard';d.innerHTML='<div class="leadTop"><div><h3>'+esc(l.name)+'</h3><p class="address">'+esc(l.address||'endereço não cadastrado')+'</p></div><span class="source">'+esc(l.source||'lead')+'</span></div><div class="meta"><span>'+(l.website?'tem site':'sem site cadastrado')+'</span>'+(l.phone?'<span>'+esc(l.phone)+'</span>':'<span>sem telefone</span>')+'</div><div class="actions">'+(selectable?'':'<button class="saveBtn">salvar</button>')+(l.phone?'<a class="waBtn" target="_blank" href="https://wa.me/'+l.phone.replace(/\D/g,'')+'">WhatsApp</a>':'')+(l.mapsUrl?'<a class="mapBtn" target="_blank" href="'+esc(l.mapsUrl)+'">mapa</a>':'')+'</div>';if(selectable)d.onclick=()=>pick(l.id);else d.querySelector('.saveBtn').onclick=()=>save(l);return d}
function renderResults(){const r=$('#results');r.innerHTML='';if(!results.length){r.innerHTML='<div class="empty"><strong>nenhum lead.</strong><span>Tente outra busca.</span></div>';return}results.forEach(l=>r.appendChild(card(l)))}
function draw(){markers.forEach(m=>m.remove());markers=[];results.forEach(l=>{const m=L.marker([l.lat,l.lng]).addTo(map).bindPopup('<b>'+esc(l.name)+'</b><br>'+esc(l.address||''));markers.push(m)});if(markers.length)map.fitBounds(L.featureGroup(markers).getBounds().pad(.12))}
function save(l){if(saved.some(x=>x.id===l.id))return;saved.unshift({...l,stage:'new'});persist();pipeline();copilot()}
function pipeline(){const root=$('#pipeline');root.innerHTML='';stages.forEach(([id,label])=>{const col=document.createElement('section');col.className='column';const ls=saved.filter(x=>(x.stage||'new')===id);col.innerHTML='<div class="columnHead"><b>'+label+'</b><span>'+ls.length+'</span></div>';ls.forEach(l=>{const d=document.createElement('article');d.className='deal';d.innerHTML='<h4>'+esc(l.name)+'</h4><p>'+esc(l.address||'')+'</p><select>'+stages.map(([sid,sl])=>'<option value="'+sid+'" '+(sid===id?'selected':'')+'>'+sl+'</option>').join('')+'</select><div class="dealActions"><button>copiloto</button><button>remover</button></div>';const bs=d.querySelectorAll('button');d.querySelector('select').onchange=e=>{l.stage=e.target.value;persist();pipeline()};bs[0].onclick=()=>{pick(l.id);view('copilot')};bs[1].onclick=()=>{saved=saved.filter(x=>x.id!==l.id);persist();pipeline();copilot()};col.appendChild(d)});root.appendChild(col)})}
function copilot(){const r=$('#copilotLeads');r.innerHTML='';saved.forEach(l=>r.appendChild(card(l,true)))}
function pick(id){selected=id;const l=saved.find(x=>x.id===id);$('#selectedLead').textContent=l?l.name+' · '+(l.address||'sem endereço'):'Nenhum lead selecionado.'}
async function search(e){e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='buscando…';try{const q={city:$('#city').value.trim(),niche:$('#niche').value,radius:Number($('#radius').value)};const r=await fetch('/api/leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(q)}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha');results=d.leads||[];$('#resultTitle').textContent=results.length+' leads';$('#providerLabel').textContent=d.provider||'';renderResults();draw();stats()}catch(x){$('#results').innerHTML='<div class="empty"><strong>busca indisponível.</strong><span>'+esc(x.message)+'</span></div>'}finally{b.disabled=false;b.textContent='buscar leads'}}
async function generate(){const l=saved.find(x=>x.id===selected);if(!l){$('#generatedText').textContent='Selecione um lead salvo primeiro.';return}const r=await fetch('/api/prospect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lead:l,goal,notes:$('#notes').value.trim()})}),d=await r.json();$('#generatedText').textContent=d.text||d.error||'Sem resposta.'}
function exportCsv(){const cols=['name','address','phone','mapsUrl','stage'];const q=v=>'"'+String(v||'').replace(/"/g,'""')+'"';const csv=[cols.join(','),...saved.map(l=>cols.map(c=>q(l[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='leads.csv';a.click()}
function view(n){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+n+'View').classList.add('active');$$('.navitem[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===n));if(n==='discovery')setTimeout(()=>map.invalidateSize(),30)}
$('#searchForm').onsubmit=search;$('#generateBtn').onclick=generate;$('#exportBtn').onclick=exportCsv;$('#clearSearch').onclick=()=>{results=[];renderResults();stats();markers.forEach(m=>m.remove());markers=[]};$$('.navitem[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('.goal').forEach(b=>b.onclick=()=>{$$('.goal').forEach(x=>x.classList.remove('active'));b.classList.add('active');goal=b.dataset.goal});$('#copyBtn').onclick=()=>navigator.clipboard.writeText($('#generatedText').textContent);stats();pipeline();copilot();
`;
