import LANDING from "./landing.js";
import APP_HTML from "./app-html.js";
import APP_JS from "./app-v5.js";
import APP_CSS from "./app-css-v2.js";
import MEMBERS from "./members.js";

const NICHE_LABELS={dentist:'dentist',clinic:'clinic',lawyer:'legal services',architect:'architect',accountant:'accountant',physiotherapy:'physiotherapy',salon:'beauty salon',gym:'fitness club',restaurant:'restaurant',real_estate:'real estate agents'};
const NICHE_TO_OSM={dentist:'["amenity"="dentist"]',clinic:'["amenity"="clinic"]',lawyer:'["office"="lawyer"]',architect:'["office"="architect"]',accountant:'["office"="accountant"]',physiotherapy:'["healthcare"="physiotherapist"]',salon:'["shop"="hairdresser"]',gym:'["leisure"="fitness_centre"]',restaurant:'["amenity"="restaurant"]',real_estate:'["office"="estate_agent"]'};
const GENERIC=new Set(['empresa local','empresa','business','dentista','clinic','clínica','advogado','arquiteto','contador','fisioterapia','academia','restaurante','imobiliária']);
const STOP=new Set(['de','da','do','das','dos','e','ltda','me','sa','advogado','advogados','advocacia','sociedade','odontologia','clinica','clínica','consultorio','consultório','arquitetura','contabilidade','imobiliaria','imobiliária','restaurante','academia','studio','centro']);
const FREE_EMAIL=new Set(['gmail.com','hotmail.com','outlook.com','yahoo.com','icloud.com','live.com','bol.com.br','uol.com.br','terra.com.br']);
const NON_OFFICIAL=['facebook.com','instagram.com','linkedin.com','youtube.com','tiktok.com','x.com','twitter.com','jusbrasil.com.br','econodata.com.br','cnpj.biz','reclameaqui.com.br','guiamais.com.br','apontador.com.br'];

const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8'}});
const text=(x,t='text/html; charset=utf-8')=>new Response(x,{headers:{'content-type':t}});
const cleanPhone=v=>String(v||'').replace(/[^\d+]/g,'');
const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function cleanName(v=''){const n=String(v).replace(/\s+/g,' ').trim();if(!n||n.length<2||GENERIC.has(n.toLowerCase())||/^\d+[a-z]?$/i.test(n)||/^(rua|avenida|av\.|alameda|travessa|praça|praca|largo|rodovia|estrada|viela|beco)\b/i.test(n))return'';return n}
function tokens(v=''){return normalize(v).split(/\s+/).filter(x=>x.length>1&&!STOP.has(x)).slice(0,7)}
function similarity(a,b){const x=tokens(a),y=new Set(tokens(b));return x.length?x.filter(t=>y.has(t)).length/x.length:0}

async function nominatim(params){const u=new URL('https://nominatim.openstreetmap.org/search');Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u,{headers:{'User-Agent':'site-sales-os/1.0','Accept-Language':'pt-BR,pt;q=0.9'}});if(!r.ok)throw Error(`Geocoding indisponível (${r.status})`);return r.json()}
async function geocodeCity(city){const rows=await nominatim({q:`${city}, Brasil`,format:'jsonv2',limit:1,countrycodes:'br'});if(!rows[0])throw Error('Cidade não encontrada.');return{lat:Number(rows[0].lat),lng:Number(rows[0].lon)}}

function mapTomTom(r){const p=r.poi||{},pos=r.position||{},website=p.url||'';return{id:`tt-${r.id}`,placeId:r.id,source:'tomtom',verificationBasis:'tomtom',name:cleanName(p.name),address:r.address?.freeformAddress||'',lat:Number(pos.lat),lng:Number(pos.lon),phone:cleanPhone(p.phone),email:'',website:website&&/^https?:/i.test(website)?website:website?`https://${website}`:'',mapsUrl:Number.isFinite(Number(pos.lat))?`https://www.openstreetmap.org/?mlat=${pos.lat}&mlon=${pos.lon}#map=18/${pos.lat}/${pos.lon}`:'',rating:null,reviews:0,type:(p.categories||[])[0]||'',instagram:'',status:'new',websiteStatus:website?'found':'unverified'}}
async function tomtomSearch(q,env){if(!env.TOMTOM_API_KEY)return null;const{city='São Paulo',niche='dentist',radius=7000}=q,center=await geocodeCity(city),term=NICHE_LABELS[niche]||niche,u=new URL(`https://api.tomtom.com/search/2/categorySearch/${encodeURIComponent(term)}.json`);u.searchParams.set('key',env.TOMTOM_API_KEY);u.searchParams.set('lat',center.lat);u.searchParams.set('lon',center.lng);u.searchParams.set('radius',Math.min(Math.max(Number(radius)||7000,1000),20000));u.searchParams.set('limit','100');u.searchParams.set('countrySet','BR');u.searchParams.set('language','pt-BR');const r=await fetch(u);if(!r.ok)throw Error(`TomTom ${r.status}`);const d=await r.json();return{center,provider:'tomtom',leads:(d.results||[]).map(mapTomTom).filter(x=>x.name&&x.lat&&x.lng)}}

function osmName(t={}){for(const x of [t.name,t['name:pt'],t.brand,t.operator,t.official_name,t.short_name,t.alt_name,t['contact:name']]){const n=cleanName(x);if(n)return n}return''}
function osmLead(el){const t=el.tags||{},lat=el.lat??el.center?.lat,lng=el.lon??el.center?.lon,name=osmName(t),website=t.website||t['contact:website']||'';if(!name)return null;return{id:`osm-${el.type}-${el.id}`,source:'osm',verificationBasis:'osm',name,address:[t['addr:street'],t['addr:housenumber'],t['addr:suburb'],t['addr:city']].filter(Boolean).join(', '),lat,lng,phone:cleanPhone(t.phone||t['contact:phone']),email:t.email||t['contact:email']||'',website,mapsUrl:`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lng}#map=18/${lat}/${lng}`,rating:null,reviews:0,type:t.amenity||t.office||t.shop||t.healthcare||t.leisure||'',instagram:t.instagram||t['contact:instagram']||'',status:'new',websiteStatus:website?'found':'unverified'}}

async function leadsHandler(request,env){if(request.method!=='POST')return json({error:'Method not allowed'},405);try{const q=await request.json();if(env.TOMTOM_API_KEY){const tt=await tomtomSearch(q,env);return json({...q,provider:tt.provider,center:tt.center,count:tt.leads.length,leads:tt.leads,capabilities:{tomtomPlaces:true,webSearch:!!env.BRAVE_SEARCH_API_KEY}})}const{city='São Paulo',niche='dentist',radius=7000}=q,center=await geocodeCity(city),filter=NICHE_TO_OSM[niche]||'["name"]',r=Math.min(Math.max(Number(radius)||7000,1000),20000);return json({city,niche,provider:'openstreetmap-browser',center,overpassQuery:`[out:json][timeout:15];(nwr${filter}(around:${r},${center.lat},${center.lng}););out center tags 80;`,count:0,leads:[],capabilities:{tomtomPlaces:false,webSearch:!!env.BRAVE_SEARCH_API_KEY}})}catch(e){return json({error:e.message||'Erro na busca'},500)}}

async function fallbackHandler(request){if(request.method!=='POST')return json({error:'Method not allowed'},405);try{const{city='São Paulo',niche='dentist',radius=7000}=await request.json(),center=await geocodeCity(city),rows=await nominatim({q:`${NICHE_LABELS[niche]||niche}, ${city}, Brasil`,format:'jsonv2',limit:40,countrycodes:'br',addressdetails:1,extratags:1,namedetails:1});const leads=[];for(const p of rows||[]){const x=p.extratags||{},name=cleanName(p.namedetails?.name||p.name||String(p.display_name||'').split(',')[0]);if(!name)continue;const lat=Number(p.lat),lng=Number(p.lon);if(Math.hypot((lat-center.lat)*111320,(lng-center.lng)*111320*Math.cos(center.lat*Math.PI/180))>radius)continue;leads.push({id:`nom-${p.place_id}`,source:'nominatim',verificationBasis:'osm',name,address:p.display_name||'',lat,lng,phone:cleanPhone(x.phone||x['contact:phone']),email:x.email||'',website:x.website||'',mapsUrl:`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lng}#map=18/${lat}/${lng}`,websiteStatus:x.website?'found':'unverified'})}return json({provider:'nominatim-fallback',center,count:leads.length,leads:leads.slice(0,40)})}catch(e){return json({error:e.message},500)}}

function candidateDomains(l){const s=new Set(),emailDomain=l.email?String(l.email).split('@').pop()?.toLowerCase():'';if(emailDomain&&!FREE_EMAIL.has(emailDomain))s.add(emailDomain);const t=tokens(l.name),base=t.join(''),hyphen=t.join('-');if(base.length>=5){s.add(`${base}.com.br`);s.add(`${base}.com`);if(/advog|lawyer/i.test(l.type||l.name))s.add(`${base}.adv.br`)}if(hyphen.length>=5)s.add(`${hyphen}.com.br`);return[...s].slice(0,6)}
function pageMatches(html,name){const txt=normalize(String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')),t=tokens(name).filter(x=>x.length>=3);return t.length>0&&t.filter(x=>txt.includes(x)).length>=Math.min(2,t.length)}
async function probe(url,name,trust=false){try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),4500),r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{'User-Agent':'Mozilla/5.0 SiteSalesOS/1.0','Range':'bytes=0-49151'}});clearTimeout(timer);if(r.status>=400)return null;const body=(r.headers.get('content-type')||'').includes('text/html')?(await r.text()).slice(0,100000):'';if(trust||pageMatches(body,name))return r.url||url}catch{}return null}
function nonOfficial(url){try{const h=new URL(url).hostname.replace(/^www\./,'');return NON_OFFICIAL.some(x=>h===x||h.endsWith('.'+x))}catch{return true}}
async function braveVerify(l,env){if(!env.BRAVE_SEARCH_API_KEY)return{checked:false};try{const u=new URL('https://api.search.brave.com/res/v1/web/search');u.searchParams.set('q',`"${l.name}" ${l.address||''}`.slice(0,350));u.searchParams.set('country','BR');u.searchParams.set('count','8');const r=await fetch(u,{headers:{Accept:'application/json','X-Subscription-Token':env.BRAVE_SEARCH_API_KEY}});if(!r.ok)return{checked:false};const d=await r.json();for(const x of d.web?.results||[]){if(!x.url||nonOfficial(x.url)||similarity(l.name,`${x.title} ${x.description}`)<.34)continue;const found=await probe(x.url,l.name);if(found)return{checked:true,found:true,website:found}}return{checked:true,found:false}}catch{return{checked:false}}}
async function verifyOne(l,env){if(l.website)return{id:l.id,websiteStatus:'found',website:l.website,evidence:'source-website',sources:[l.source]};const b=await braveVerify(l,env);if(b.found)return{id:l.id,websiteStatus:'found',website:b.website,evidence:'brave-web',sources:['brave-web']};const emailDomain=l.email?String(l.email).split('@').pop()?.toLowerCase():'';for(const d of candidateDomains(l)){const found=await probe(`https://${d}/`,l.name,!!emailDomain&&d===emailDomain&&!FREE_EMAIL.has(d));if(found)return{id:l.id,websiteStatus:'found',website:found,evidence:'domain-probe',sources:[...(b.checked?['brave-web']:[]),'domain-probe']}}const high=l.verificationBasis==='tomtom'&&b.checked;return{id:l.id,websiteStatus:high?'no_site_signal':'unverified',website:'',evidence:high?'tomtom-no-url+brave-no-domain':'insufficient-sources',sources:b.checked?['brave-web']:[]}}
async function verifyHandler(request,env){if(request.method!=='POST')return json({error:'Method not allowed'},405);try{const{leads=[]}=await request.json(),out=[];for(let i=0;i<Math.min(leads.length,12);i+=3)out.push(...await Promise.all(leads.slice(i,i+3).map(l=>verifyOne(l,env))));return json({results:out,capabilities:{tomtomPlaces:!!env.TOMTOM_API_KEY,webSearch:!!env.BRAVE_SEARCH_API_KEY}})}catch(e){return json({error:e.message},500)}}

async function prospect(request){if(request.method!=='POST')return json({error:'Method not allowed'},405);const{lead={},goal='first-contact'}=await request.json(),n=lead.name||'sua empresa';const texts={followup:`Oi! Retomando a mensagem sobre o site da ${n}. Posso montar uma prévia objetiva para você avaliar sem compromisso.`,proposal:`Proposta — ${n}\n\nPágina responsiva, apresentação do negócio, serviços, localização, WhatsApp, SEO básico e publicação.`, 'objection-price':`Podemos começar com uma versão enxuta para a ${n}, focada em apresentação e contato. Posso te passar o escopo mínimo e o valor.`};return json({provider:'template',text:texts[goal]||`Oi! Encontrei a ${n} pesquisando negócios da região. Posso montar uma prévia do site antes de qualquer compromisso. Se eu te enviar uma ideia inicial, você consegue dar uma olhada?`})}

export default{async fetch(request,env){const p=new URL(request.url).pathname;if(p==='/api/health')return json({ok:true,service:'site-sales-os',version:10,capabilities:{tomtomPlaces:!!env.TOMTOM_API_KEY,webSearch:!!env.BRAVE_SEARCH_API_KEY}});if(p==='/api/leads')return leadsHandler(request,env);if(p==='/api/fallback-leads')return fallbackHandler(request);if(p==='/api/verify-websites')return verifyHandler(request,env);if(p==='/api/prospect')return prospect(request);if(p==='/app/app.js')return text(APP_JS,'application/javascript; charset=utf-8');if(p==='/app/styles.css')return text(APP_CSS,'text/css; charset=utf-8');if(p==='/app'||p==='/app/')return text(APP_HTML);if(p==='/members'||p==='/members/')return text(MEMBERS);if(p==='/'||p==='/index.html')return text(LANDING);return new Response('Not found',{status:404})}};
